// Code below was generated by ChatGPT, from prompt:
// ```
// Write a function in TypeScript that returns a randomly generated (nice looking) color.
// The function should have a side effect that it adds this color to a list and only
// generates colors that are visually distinct from the colors already in this list.
// ```

type HSLColor = {
  h: number; // 0–360
  s: number; // 0–100
  l: number; // 0–100
};

const generatedColors: HSLColor[] = [];

// Tunable constants
const MIN_HUE_DISTANCE = 35; // degrees
const MIN_LIGHTNESS_DISTANCE = 12; // %
const MAX_ATTEMPTS = 100;

function randomBetween(min: number, max: number): number {
  return Math.random() * (max - min) + min;
}

function hslDistance(a: HSLColor, b: HSLColor): number {
  const hueDiff = Math.min(Math.abs(a.h - b.h), 360 - Math.abs(a.h - b.h));

  const lightnessDiff = Math.abs(a.l - b.l);

  // Hue matters most, lightness a bit
  return hueDiff + lightnessDiff * 0.5;
}

function isDistinct(color: HSLColor): boolean {
  return generatedColors.every((existing) => {
    const hueDiff = Math.min(
      Math.abs(color.h - existing.h),
      360 - Math.abs(color.h - existing.h),
    );

    if (hueDiff < MIN_HUE_DISTANCE) {
      return Math.abs(color.l - existing.l) >= MIN_LIGHTNESS_DISTANCE;
    }

    return true;
  });
}

function hslToCss({ h, s, l }: HSLColor): string {
  return `hsl(${Math.round(h)}, ${Math.round(s)}%, ${Math.round(l)}%)`;
}

/**
 * Generates a nice-looking, visually distinct color.
 * Side effect: stores the color internally.
 */
export default (): string => {
  let attempts = 0;

  while (attempts < MAX_ATTEMPTS) {
    const candidate: HSLColor = {
      h: randomBetween(0, 360),
      s: randomBetween(55, 75), // vivid but not neon
      l: randomBetween(45, 65), // readable on light & dark backgrounds
    };

    if (isDistinct(candidate)) {
      generatedColors.push(candidate);
      return hslToCss(candidate);
    }

    attempts++;
  }

  // Fallback: evenly spaced hues if space is exhausted
  const fallbackHue = (generatedColors.length * 137.508) % 360;
  const fallback: HSLColor = { h: fallbackHue, s: 65, l: 55 };
  generatedColors.push(fallback);

  return hslToCss(fallback);
};
